### ISSUE TITLE
Crash upon launch

### ISSUE THREAD

**Issue by MindFaer** [Hidoni/CustomizableElytra#1]
[crash-2021-01-31_21.48.19-fml.txt](https://github.com/Hidoni/CustomizableElytra/files/5901607/crash-2021-01-31_21.48.19-fml.txt)

Here's my crash upon launching, maybe an incompatibility with Eidolon?

**Comment by PQxDev01** [comment]
I have the same problem: 

[crash-2021-02-01_16.01.50-fml.txt](https://github.com/Hidoni/CustomizableElytra/files/5904709/crash-2021-02-01_16.01.50-fml.txt)

**Comment by Hidoni** [comment]
Looks like it was related to Performant, I put a new release on curseforge that seems to have fixed it from my testing!
