### ISSUE TITLE
Unable to join my server, but other players with 1.5.4 are able to.

### ISSUE THREAD

**Issue by antibang** [Hidoni/CustomizableElytra#10]
![Screen Shot 2021-07-16 at 6 38 06 PM](https://user-images.githubusercontent.com/79492924/126018146-b89ce11f-d362-4080-a227-b015d7ca166e.png)

I updated my modpack today and updated the mod to its most recent version, however I'm still getting this error. Though, the other players who have updated their pack are able to join. It's only affecting me right now, which I prefer over others players.

Would a log/debug be helpful? Would you need one from the server's side as well?

**Comment by Hidoni** [comment]
Your client side logs would be very helpful in figuring this out, while I don't believe the server-side logs will have any relevant info, if you can provide them too that'd be great :)

**Comment by antibang** [comment]
**Client log -**
[latest.log](https://github.com/Hidoni/CustomizableElytra/files/6833947/latest.log)

**Server log -**
[latest.log](https://github.com/Hidoni/CustomizableElytra/files/6833948/latest.log)

**Comment by antibang** [comment]
I don't know if this helps or hurts at all, but for some reason I was just able to join. I didn't do anything different. Before reporting I tried a few things to see if it made a difference like join a single-player world then attempt to log onto my server, restarting the game, old mod version on client (even tho I know it'd be incompatible) and used the CurseForge app to launch the game. I typically just use the Minecraft launcher. I got bored and decided to try again and for some reason it worked lol. Then logged off for a bit, returned and the problem happened again.

**Comment by Hidoni** [comment]
Heya, could you try logging onto the server with this version installed and updating on me on whether it fixed the issue? It should be compatible with the server even if it's still on 1.5.4!
[customizableelytra-1.16.4-1.5.5.zip](https://github.com/Hidoni/CustomizableElytra/files/6834674/customizableelytra-1.16.4-1.5.5.zip)

**Comment by antibang** [comment]
Just tried it and unfortunately it did not :( I got the same message as before

**Comment by Hidoni** [comment]
If you're still getting this issue, could you give me your mod list? I can't seem to replicate this issue from my own testing, so it might be caused from a weird edge case with another mod you have installed

**Comment by antibang** [comment]
Of course! I do happen to use maybe one or two client sided mods that aren't included in my modpack (other than OptiFine), which I don't know if that'd cause the issue. 

Here's my current mod list. If it's too messy, I'll clean it up some. I just grabbed this from a crash report that happened earlier.
https://pastebin.com/nPBJXZnE

**Comment by Hidoni** [comment]
Hmm, if there are some mods that only you use, could you tell me which ones they are specifically? if it's a compatibility issue it's likely to be from those mods

**Comment by antibang** [comment]
I believe the only mods that I use that aren't included in my pack is Better Biome Blend, CMDCam and OptiFine. I went over my mod list a few times to double check.

**Comment by Hidoni** [comment]
Hmm, those shouldn't cause those kinds of issues... could you try this version? I've tried to pretty much ensure the client creates the forge:elytra tag no matter what ^^
[customizableelytra-1.16.4-1.5.5.zip](https://github.com/Hidoni/CustomizableElytra/files/6907328/customizableelytra-1.16.4-1.5.5.zip)

**Comment by antibang** [comment]
I tried it, and it still didn't work. However, I might have found the problem... I forgot I had TerraForged in my mods (which ins't included in my main pack that everyone else on the server uses). Once I removed it, I was able to join the server no problem :p  sorry! I completely forgot about that one. I'm not sure if that's a TerraForged issue I should report or not

**Comment by Hidoni** [comment]
Yeah, seems you got unlucky haha, the specific version of TerraForged you have installed had an issue where it messed with tags too early, it seems like it was fixed in the very next version, so if you want to keep playing with TerraForged installed you just need to update it! :)
