### ISSUE TITLE
Named elytra does not preserve pattern, and reversely - patterned one does not preserve name

### ISSUE THREAD

**Issue by Toma400** [Hidoni/CustomizableElytra#12]
As in title, using my "Wings of Hope" with custom pattern, I realised after a while that they are called "Elytra" now. Thought it is a glitch, so I decided to name them, but now they have no pattern (even though pattern list is visible in GUI).

Screenshots as an example (before naming it had orange-yellowy pattern):

![2021-09-02_08 24 40](https://user-images.githubusercontent.com/65849429/131793004-add9e516-0c03-4c84-9a16-712e707037a0.png)

![2021-09-02_08 26 37](https://user-images.githubusercontent.com/65849429/131793251-8d737361-8652-4358-81d3-de56a066f047.png)

I'm using 1.5.4 version, although didn't see any bugfixes on that part in 1.5.5, so I'm assuming it wouldn't change the issue.

**Comment by Hidoni** [comment]
Thanks for reporting this!
Looks like it was partially fixed in 1.5.5, but it would still lose its name if you crafted it with a banner.
There's a new version out, 1.5.6, which should fix this fully! :)
