### ISSUE TITLE
Cape still visible with elytra when in Curious Elytra slot

### ISSUE THREAD

**Issue by Inqie** [Hidoni/CustomizableElytra#13]
The cape does not disappear when putting on a customized elytra in the curios slot used by Curious Elytra. Therefore when moving, it clips through. 

The cape does disappear, as it should, with all other combinations (eg. vanilla elytra in curios slot; customized elytra in chestplate slot). The customized elytra in the curios slot should behave like this also.

**System Info:**
Minecraft Version: 1.16.5
Forge Version: 36.2.4
Customizable Elytra Version: 1.5.6
Curious Elytra Version: 4.0.2.3
Curios Version: 4.0.5.2
Java Version: 11.0.11 64bit
CPU: 16x AMD Ryzen 9 5900HX with Radeon Graphics
GPU: NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2

**Comment by Hidoni** [comment]
Thanks for reporting this! :) Should have it fixed for the next version.

**Comment by Hidoni** [comment]
Fixed in version 1.5.7
