### ISSUE TITLE
Coins JE Banner Support

### ISSUE THREAD

**Issue by RobertHDPotatoes** [Hidoni/CustomizableElytra#16]
Not sure if this is an issue with the mod "Coins JE" or Customizable Elytra, but in my log file it says multiple lines similar to: "Using missing texture, unable to load customizableelytra:textures/entity/elytra_banner/coins" and Coins JE Banners do not visually show up when added to Customizable Elytra.

Minecraft Version: 1.16.5
Customizable Elytra Version: 1.6.0
Forge Version: 36.2.9
Latest Log: https://pastebin.com/G4f8UGch

**Comment by Hidoni** [comment]
I need to add support for mods separately, that's why you're getting that message at the moment. I'll add it for this one when I get the chance.

**Comment by RobertHDPotatoes** [comment]
Oh wow, I hadn't considered that every mod has to be supported individually by you since every other modded banner pattern works in my modpack already. Good on you for making this mod compatible with so many others!

**Comment by Hidoni** [comment]
Thanks! :)
I've uploaded a new version to Curseforge (1.6.1) that should work with banners from that mod!
