### ISSUE TITLE
Server crashed 

### ISSUE THREAD

**Issue by LazarZegrea** [Hidoni/CustomizableElytra#17]
Here's the logs https://mclo.gs/YdVWn47

**Comment by Hidoni** [comment]
I'm not sure what makes you believe this is an issue related to my mod, according to the log you got an unhandled OutOfMemoryError in the server right before it crashed, seems to me like your server just genuinely ran out of RAM. If you've got some other crash log that shows a crash related to my mod, I'd be happy to see it.

**Comment by Hidoni** [comment]
Closing this, feel free to reopen if you have other logs that indicate this is related to Customizable Elytra.
