### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by WenXin20** [Hidoni/CustomizableElytra#2]
`Minecraft v1.16.5`
`Forge v36.0.7`
`CE v1.0.1`

Is this mod client only? It crashed my server.
[Crash Report](https://gist.github.com/WenXin20/bfa61a8f2efb7b7b56861ab9a231bdb2)

**Comment by Hidoni** [comment]
Oh, I think I forgot to register the client events exclusively client-side, I'll release a fix for it tomorrow.

**Comment by WenXin20** [comment]
Thanks!

**Comment by Hidoni** [comment]
I posted a new version on curseforge that from my testing seems to fix it!

**Comment by WenXin20** [comment]
Alright, I'll give it a try later today

**Comment by WenXin20** [comment]
Yup, it's fixed. :)
