### ISSUE TITLE
Not showing in curios cosmetic slot

### ISSUE THREAD

**Issue by DoctorMage** [Hidoni/CustomizableElytra#21]
Mods included

caelus-forge-1.16.5-2.1.3.2.jar
ColtCosmeticArmorMod-1.2.5.jar
CosmeticArmorReworked-1.16.5-v5.jar
curiouselytra-forge-1.16.5-4.0.2.4.jar
curios-forge-1.16.5-4.0.8.2.jar
customizableelytra-1.16.4-1.6.1.jar
relics-1.16.5-0.3.4.3.jar

Forge Version : 36.2.34

When put in cosmetic back slot elytra will not show and also disables appearnace of other items in back slot
using relics as comparsion
unsure which mod enables the slot but I know colts cosmetic armor does

https://streamable.com/y1795k

**Comment by Hidoni** [comment]
Thanks for reporting but I don't think this is an issue with this mod. The only part where customizable elytra interacts with 1.16 is in this part of the code: https://github.com/Hidoni/CustomizableElytra/blob/ea60a8eeeb829de39200134d6d2cda2d445ff62c/src/main/java/com/hidoni/customizableelytra/util/ElytraInventoryUtil.java#L26-L32  
It uses the curios API to get the item, which is then used in rendering if it exists. No other code interacts with curios and thus I don't believe it is at fault here. Perhaps one of your other mods that interacts more with curios is responsible.

**Comment by DoctorMage** [comment]
Alright then thanks for the update
