### ISSUE TITLE
Incompability with Additional Banners

### ISSUE THREAD

**Issue by RedBeast1959** [Hidoni/CustomizableElytra#22]
Minecraft: 1.19.2
Forge: 43.1.1
Customizable Elytra: customizableelytra-1.19.0-1.7.1.jar
Additional Banners: AdditionalBanners-Forge-1.19.2-10.0.1.jar

Other mods:
Bookshelf-Forge-1.19.2-16.0.3.jar
caelus-forge-1.19.2-3.0.0.6.jar
curios-forge-1.19.2-5.1.1.0.jar
elytraslot-forge-6.0.0+1.19.2.jar

FAQ says Additional Banners mod is compatible. But current latest forge version, Elytra doesn't show any pattern of the modded banners. Dyeing Elytra and placing vanilla banner pattern to Elytra works fine though.

**Comment by Hidoni** [comment]
Thanks for reporting this! Seems that they updated the names of the banenrs internally in 1.19 which meant that this mod couldn't find them. It also seems like the mod has added more banners since I last checked, so I've gone ahead and made them all work again, including the new ones :)
