### ISSUE TITLE
Unable to convert to vanilla Elytra

### ISSUE THREAD

**Issue by GoldenFurredFox** [Hidoni/CustomizableElytra#28]
Putting a Customizable Elytra alone in the crafting table splits the wings and removes their dye colors instead on converting it to a vanilla Elytra like the mod page says.

Customizable Elytra version 1.6.5 for 1.19.3

**Comment by Hidoni** [comment]
My bad, the description on the mod page is outdated. In newer versions right clicking on a cauldron will turn your elytra back into a vanilla one!
