### ISSUE TITLE
Incompatible with MorePlayerModels

### ISSUE THREAD

**Issue by xLoadingx** [Hidoni/CustomizableElytra#30]
After spending a considerable amount of time going through my 91 mods, I have identified the culprit behind the issue I am facing. It appears that the MorePlayerModels mod is causing the problem. Although it does not cause any crashes, the elytra do not show up on the player's back. Even though the custom-made elytra can be worn, they do not appear on the back and the player appears to be lying down while flying around with no elytra.

**Comment by Hidoni** [comment]
What version of the mod are you using?
