### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by DeathAngel1374** [Hidoni/CustomizableElytra#32]
Are you planning on releasing the mod for 1.20.2 onwards? I hope this is the right place to ask, if not I'm really sorry for the trouble

**Comment by Hidoni** [comment]
Yeah, I am! Unfortunately Quilt has had delays in support for 1.20.2, but promises to have an update soon, since the mod supports all 3 mod loaders rn, I would rather wait a bit to make a release for all 3 at once instead of porting at separate times

**Comment by DeathAngel1374** [comment]
Ah ok I understand, tyvm

**Comment by Hidoni** [comment]
Released now :)
