### ISSUE TITLE
Compatibility issue.

### ISSUE THREAD

**Issue by michaelukz** [Hidoni/CustomizableElytra#33]
There seems to be a compatibility between CustomizableElytra and Skillcloaks.

When trying to equip a skillcloak with a custom elytra equipped it crashes the game, and attempting to rejoin will instantly crash again making a single player world unplayable without NBTEdit.

Attached is the crash report.
[crash-2023-10-29_01.35.47-client.txt](https://github.com/Hidoni/CustomizableElytra/files/13230303/crash-2023-10-29_01.35.47-client.txt)

**Comment by Hidoni** [comment]
Thanks for reporting the issue! This appears to have fixed the crash from my testing, but I'd appreciate it if you could check too! 
 
[customizableelytra-forge-2.1.1+1.20.zip](https://github.com/Hidoni/CustomizableElytra/files/13231359/customizableelytra-forge-2.1.1%2B1.20.zip)

**Comment by michaelukz** [comment]
Wow, Insanely fast fix!
