### ISSUE TITLE
[Suggestion] Remove the recipe combining two Elytra Wings together becoming one Wing with no data

### ISSUE THREAD

**Issue by PokeMaserJ** [Hidoni/CustomizableElytra#36]
There is a conflicting recipe with the singular Elytra Wings. One where it becomes the custom Elytra, and the other wiping all data off both and becoming a single wing (durability based maybe?) . Can imagine people accidently doing the later, and Vanilla doesn't have a way to solve the issue of conflicting recipes, you need a mod like Polymorph .

**Comment by Hidoni** [comment]
What version of Minecraft and the mod are you using?

**Comment by PokeMaserJ** [comment]
Sorry guess I should have mentioned that lol, customizableelytra-forge-2.1.1+1.20 is the jar

**Comment by Hidoni** [comment]
I can't seem to replicate this.  
Are you using any other mods or just this one?

**Comment by PokeMaserJ** [comment]
Let me try with just this. Hoping it's not some cross mod conflict.

**Comment by PokeMaserJ** [comment]
Some cross mod thing. *sigh*

**Comment by PokeMaserJ** [comment]
So it's not a cross mod issue it turns out. 
![Elytra](https://github.com/Hidoni/CustomizableElytra/assets/11018346/97f0d636-dea8-4db6-aae2-c9b6966d8e7f)
This is a image of my mods folder and a grab from in game with the mod "Poly-Morph" allowing me to choose what recipe if the inputs have multiple outputs.

**Comment by Hidoni** [comment]
This has been fixed in the latest version! ^^
