### ISSUE TITLE
Suggestion to change "Elytra wing" to "Elytron"

### ISSUE THREAD

**Issue by FierceDIO** [Hidoni/CustomizableElytra#37]
Not an issue, but I think it would make more sense if the item was called "Elytron" as that is the singular form of the word "Elytra".

**Comment by Hidoni** [comment]
🤓  
More seriously though: someone pointed this out over a year ago but I think most people don't actually know that Elytra is the plural form of Elytron so for most people it would be more confusing if it the item was named that so I'll probably leave it as it is for now 😅
