### ISSUE TITLE
[1.21] After Installing mod on latest version the game ccrash

### ISSUE THREAD

**Issue by Periam** [Hidoni/CustomizableElytra#38]
Installed the mod on latest MC version and the game crash

Minecraftr 1.21
Forge 51.0.8
customizableelytra-forge-2.2.3+1.21

Crash Log

[crash-2024-06-15_12.06.06-client.txt](https://github.com/user-attachments/files/15848311/crash-2024-06-15_12.06.06-client.txt)

**Comment by Hidoni** [comment]
Wow, I can't believe I missed that, should be fixed in the new version. Thanks for reporting it!
