### ISSUE TITLE
Banner Pattern Elytras override textures beneath them.

### ISSUE THREAD

**Issue by bconlon1** [Hidoni/CustomizableElytra#4]
This is primarily an issue seen when using a Minecon cape, as even when having the cape toggled on, the banner patterns still show up on the customized elytra. This issue isn't seen as much with the other customization types like dyed elytras, as the Minecon cape texture still shows up, however depending on the dye color it causes tinting issues to the cape texture. Also somewhat related to this is an issue where the cape still renders on the player's back even with the elytra equipped.

I mainly came across this issue when attempting to setup compatibility for the Aether's capes and their elytra skins, where I was trying to get around this issue for the elytra skin textures only to realize it also applied to Minecon capes, so the priority order I was trying to set up wouldn't work (Minecon Cape overrides Aether Cape overrides Customizable Elytra Texture, unless Minecon Cape and/or Aether Cape rendering is disabled). Setting up a PR for this compatibility would likely be much easier if some change were made to let textures like the ones of the Minecon capes to override the customizable elytra rendering to fix this issue.

**Comment by Hidoni** [comment]
> This is primarily an issue seen when using a Minecon cape, as even when having the cape toggled on, the banner patterns still show up on the customized elytra. This issue isn't seen as much with the other customization types like dyed elytras, as the Minecon cape texture still shows up, however depending on the dye color it causes tinting issues to the cape texture.

Unless I'm misunderstanding, it sounds like you're describing the intended behavior of both types of customization, the banner pattern customization intentionally doesn't show the cape texture, the banner is rendered layer by layer, starting with the banner base, which would cover the any cape texture anyway.
As for the dye customization, it looks far worse on cape texture, but the only fix for that would be to create a white version of every cape in the game, which there are 22 of so far, and then who knows how many capes from other mods, and dynamically replacing them when they're about to be rendered, which I currently don't have time to implement unfortunately, so for now it'll have to stay as-is, tinting the existing cape texture instead.

> Also somewhat related to this is an issue where the cape still renders on the player's back even with the elytra equipped.

Thanks for reporting this, I've fixed this and I'll publish a new version on curseforge with it fixed.

> f some change were made to let textures like the ones of the Minecon capes to override the customizable elytra rendering to fix this issue.

Again, unless I'm misunderstanding you, you're suggesting that if the user has a cape, that its texture should completely override the customizable elytra rendering? that sounds completely pointless, if you have a vanilla cape and want to use its elytra texture, you can just not customize your elytra and equip a vanilla one,

**Comment by bconlon1** [comment]
> Again, unless I'm misunderstanding you, you're suggesting that if the user has a cape, that its texture should completely override the customizable elytra rendering? that sounds completely pointless, if you have a vanilla cape and want to use its elytra texture, you can just not customize your elytra and equip a vanilla one,

My reasoning was that, it just seems easier for player usability for the cape to override the customizable elytra rendering _unless_ the player has their Minecon cape toggled off using the button in skin customization settings. Therefore, the player can see their cape by default, but if they want to see the customized elytra instead they can simply toggle that cape button, instead of them always seeing the customized elytra and having to switch out for another elytra if they want to see their Minecon cape. I wasn't sure what the intended behavior was though when I first noticed this, I was just thinking of what made the most sense to me.

> As for the dye customization, it looks far worse on cape texture, but the only fix for that would be to create a white version of every cape in the game, which there are 22 of so far, and then who knows how many capes from other mods, and dynamically replacing them when they're about to be rendered, which I currently don't have time to implement unfortunately, so for now it'll have to stay as-is, tinting the existing cape texture instead.

Also regarding this wouldn't it work to just, if you want to keep the customized elytras having priority over the cape skins, make it so if you have a cape active have it so the cape texture isn't passed to the dyed elytra renderer and instead the regular elytra texture is? Or just render another texture layered on top of it similar to how you do with the banner elytras. Although I guess my prior argument about the cape button can be applied here that I think players can just turn off their cape if they don't want to encounter this issue.

**Comment by bconlon1** [comment]
Although I suppose it could still be considered more of a hassle for the player to have to toggle their cape every time they take the elytra off to get it to reappear so, I'm not sure. You're the mod dev so the decision is yours to make, I can work on compatibility based on whatever priority of rendering on the elytra that you think is best.

**Comment by Hidoni** [comment]
Sorry for taking so long, but I finally had some free time to improve how the mod handles capes and as a result, have opted to have elytra customized with banners use the cape as the base pattern by default.
While it's not a full override like you originally suggested, it's definitely very visible ([See here for an example](https://i.imgur.com/zuYwiTq.png)) as long as you don't cover your entire banner in patterns now, and if you still want to add support for your mod feel free to do so! :)
