### ISSUE TITLE
Crash while casting DownloadingTexture to SimpleTextureInvoker

### ISSUE THREAD

**Issue by bconlon1** [Hidoni/CustomizableElytra#6]
I'm unsure whether this is something happening just on my end, but the grayscale texture util seems to be failing to convert elytra cape textures. When making a banner or dyed elytra and equipping it while a cape is active, the game crashes once you try to view it in third person.
[crash-2021-06-26_19.16.48-client.txt](https://github.com/Hidoni/CustomizableElytra/files/6720920/crash-2021-06-26_19.16.48-client.txt)

**Comment by Hidoni** [comment]
Thanks for the report, I couldn't exactly reproduce the crash on my end, even when the cape was definitely a DownloadingTexture, but I've pushed a fix that should handle edge cases with texture types, let me know if the crash still occurs!

**Comment by bconlon1** [comment]
Ended up having to re-setup the workspace but it works now, I recently moved computers so maybe something had broken in the workspace when I moved it over.
