### ISSUE TITLE
Infinite Elytra Durability by crafting into Elytra Wings

### ISSUE THREAD

**Issue by Partonetrain** [Hidoni/CustomizableElytra#8]
![image](https://user-images.githubusercontent.com/19861808/124841232-6208fa80-df52-11eb-99a0-e9a4f0147804.png)
![image](https://user-images.githubusercontent.com/19861808/124841377-b613df00-df52-11eb-9806-017fd51dbce7.png)

Pretty easy to just cycle this every time you get low on durability. The Elytra Wing recipe needs to match 0 damage.

**Comment by Hidoni** [comment]
Thanks for reporting, I've fixed this in version 1.5.3
