### ISSUE TITLE
Mod isn't able to be played on multi-player

### ISSUE THREAD

**Issue by LuisRandomness** [Hidoni/CustomizableElytra#9]
**Minecraft 1.16.5 - Forge v36.1.33 - CE V1.5.3**

Opening a multiplayer server with Customizable Elytra will cause clients connecting to it to get disconnected with this message:
![](https://cdn.discordapp.com/attachments/864154893954449418/864827969683324938/2021-07-14_11.59.11.png)

[Here are the server and client logs for more information about the issue.](https://gist.github.com/LuisRandomness/1484b0d403b7692aad8f71592373b789)

**Comment by Hidoni** [comment]
Thanks for reporting this!
Should be fixed on the newest version, 1.5.4 :)
